services:
  redis:
    image: redis:7.4.2-alpine
    ports:
      - "127.0.0.1:6379:6379"
  postgres:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_PASSWORD: dev
    ports:
      - 127.0.0.1:5432:5432
  rabbitmq:
    image: rabbitmq:4.0.7-alpine
    ports:
      - 127.0.0.1:5672:5672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "node_health_check"]
      interval: 10s
      timeout: 5s
  api:
    build: api
    ports:
      - 127.0.0.1:3000:3000
      - 127.0.0.1:9464:9464
    environment:
      DATABASE_URL: "postgresql://postgres:dev@postgres:5432/api"
      AMQP_URL: "amqp://guest:guest@rabbitmq:5672" 
      PROMETHEUS_EXPORTER_PORT: 9464
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./api/secret:/app/secret 
    develop:
      watch:
        - action: sync+restart
          path: ./api
          target: /api
  transaction-consumer:
    build: transactionConsumer
    ports:
      - 127.0.0.1:9465:9464
    environment:
      AMQP_URL: "amqp://guest:guest@rabbitmq:5672" 
      DATABASE_URL: "postgresql://postgres:dev@postgres:5432/api"
    depends_on:
      rabbitmq:
        condition: service_healthy
