---
- name: Keyrings folder is present
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "1755"

- name: Docker apt repository GPG key is present
  become: true
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/debian/gpg"
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Docker apt repository is present
  become: true
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable"
    mode: "644"

- name: Docker is installed
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest
    update_cache: true

- name: rsync in installed
  become: true
  ansible.builtin.apt:
    name:
      - rsync
    state: latest
    update_cache: true
